title: NFM 2026
preposition: ''
description: NASA Formal Methods Symposium (NFM) 2026<br>
              University of Southern California<br>
              Los Angeles, California, USA<br>
              May 5-7, 2026

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.3"

plugins:
  - jekyll-include-cache

# Site configuration
baseurl: ""
url: "https://nfm2026.github.io"

conference:

  # Navigation bar
  navigation:
    logo:
      name: JPL
      url: 'https://www.jpl.nasa.gov/'
    links:
      - name: Home
        relative_url: /
      - name: Committees
        relative_url: /committees/
      - name: Call for Papers
        relative_url: /cfp/
      - name: Keynote Speakers
        relative_url: /keynote_speakers/
      - name: Workshop
        relative_url: /workshop/
      - name: Venue
        relative_url: /venue/
      - name: Previous Symposiums
        relative_url: /history/

